spring.application.name=demo

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d86qspd7vvec73aid0d0-a.virginia-postgres.render.com:5432/data_apz6?sslmode=require
spring.datasource.username=data_apz6_user
spring.datasource.password=xwH8cKUa7abd2uQvJylBqjQBbg9GopfH

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
